#!/usr/bin/env python3
"""Generate the derived-OSCORE-context parity fixture (EDHOC -> OSCORE).

The Python oracle (python/src/lichen/crypto) runs the deterministic EDHOC
handshake from test/vectors/edhoc.json#fixed_seed_sign_sign, exports the
OSCORE master material (RFC 9528 Section 7.2.1), derives the RFC 8613
security context, and protects one fixed request. The committed fixture is
consumed by:

- python/tests/crypto/test_oscore_context_parity.py (oracle drift guard)
- rust/lichen-oscore/tests/context_parity.rs (byte-for-byte Rust parity)

Run: PYTHONPATH=python/src python3 test/vectors/generate_oscore_context_parity.py
Writes: test/vectors/oscore_context_parity.json
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from unittest.mock import patch

import cbor2

from lichen.crypto.edhoc import EdhocInitiator, EdhocResponder, OscoreContext
from lichen.crypto.identity import Identity
from lichen.crypto.oscore import MemorySecurityContext

VECTORS_DIR = Path(__file__).resolve().parent
FORMAT_VERSION = 2

EDHOC_VECTORS = VECTORS_DIR / "edhoc.json"
OUTPUT = VECTORS_DIR / "oscore_context_parity.json"

# Fixed request exercised by both implementations.
REQUEST_SEQUENCE = 0
REQUEST_CODE = 0x01
REQUEST_PAYLOAD = b"EDHOC-OSCORE-CROSS-PARITY"


def run_deterministic_handshake(
    seed_i: bytes, seed_r: bytes
) -> tuple[bytes, bytes, bytes, bytes]:
    """Run the EDHOC handshake with the vector's seeds and fixed RNG.

    Returns (master_secret, master_salt, sender_id, recipient_id) as seen by
    the initiator (sender_id == C_I, recipient_id == C_R).
    """
    identity_i = Identity.from_seed(seed_i)
    identity_r = Identity.from_seed(seed_r)

    def fake_urandom(n: int) -> bytes:
        return b"\x42" * n

    with patch.object(os, "urandom", fake_urandom):
        initiator = EdhocInitiator.create(identity_i, c_i=b"\x00")
        responder = EdhocResponder.create(identity_r, c_r=b"\x01")
        msg1 = initiator.create_message_1()
        msg2 = responder.process_message_1(msg1, identity_i.pubkey)
        msg3 = initiator.process_message_2(msg2, identity_r.pubkey)
        responder.process_message_3(msg3, identity_i.pubkey)
        ctx_i = initiator.export_oscore()
        ctx_r = responder.export_oscore()

    # Both roles must hold identical master material with swapped IDs.
    assert ctx_i.master_secret == ctx_r.master_secret
    assert ctx_i.master_salt == ctx_r.master_salt
    assert ctx_i.sender_id == ctx_r.recipient_id
    assert ctx_i.recipient_id == ctx_r.sender_id
    return ctx_i.master_secret, ctx_i.master_salt, ctx_i.sender_id, ctx_i.recipient_id


def main() -> None:
    edhoc = json.loads(EDHOC_VECTORS.read_text())
    vector = edhoc["vectors"][0]
    assert vector["name"] == "fixed_seed_sign_sign"

    seed_i = bytes.fromhex(vector["seed_i"])
    seed_r = bytes.fromhex(vector["seed_r"])

    master_secret, master_salt, sender_id, recipient_id = run_deterministic_handshake(
        seed_i, seed_r
    )

    # The exported material must match the committed EDHOC vectors exactly.
    assert master_secret.hex() == vector["oscore_master_secret"], (
        "EDHOC export no longer matches edhoc.json oscore_master_secret"
    )
    assert master_salt.hex() == vector["oscore_master_salt"], (
        "EDHOC export no longer matches edhoc.json oscore_master_salt"
    )
    assert sender_id.hex() == vector["oscore_sender_id"]
    assert recipient_id.hex() == vector["oscore_recipient_id"]

    # Derive the RFC 8613 security context from the exported material.
    ctx = MemorySecurityContext.from_edhoc(
        OscoreContext(
            master_secret=master_secret,
            master_salt=master_salt,
            sender_id=sender_id,
            recipient_id=recipient_id,
        )
    )

    # Protect one fixed request at sequence 0.
    piv = REQUEST_SEQUENCE.to_bytes(5, "big").lstrip(b"\x00") or b"\x00"
    nonce = ctx._construct_nonce(piv, sender_id, ctx.alg_aead)
    # RFC 8613 Section 8.1: 0xFF payload marker precedes non-empty payload.
    plaintext = bytes([REQUEST_CODE]) + b"\xff" + REQUEST_PAYLOAD

    alg_aead = 10
    ext_aad = cbor2.dumps([1, [alg_aead], sender_id, piv, b""])
    enc_structure = cbor2.dumps(["Encrypt0", b"", ext_aad])
    ciphertext = ctx.alg_aead.encrypt(plaintext, enc_structure, ctx.sender_key, nonce)

    flags = len(piv) | 0x08  # n bits + k bit (KID always present for requests)
    oscore_option = bytes([flags]) + piv + sender_id

    fixture = {
        "$schema": "./schema.json",
        "format_version": FORMAT_VERSION,
        "name": "oscore_context_parity",
        "description": (
            "Derived OSCORE security context parity: EDHOC-exported master "
            "material, RFC 8613 derived keys, and one protected request. "
            "Generated by the Python oracle from edhoc.json#fixed_seed_sign_sign."
        ),
        "spec": "https://www.rfc-editor.org/rfc/rfc9528#section-7.2.1",
        "source_vector": "edhoc.json#fixed_seed_sign_sign",
        "determinism": {
            "seed_i": seed_i.hex(),
            "seed_r": seed_r.hex(),
            "c_i": "00",
            "c_r": "01",
            "rng_fill_byte": "42",
        },
        "context": {
            "master_secret": master_secret.hex(),
            "master_salt": master_salt.hex(),
            "sender_id": sender_id.hex(),
            "recipient_id": recipient_id.hex(),
            "id_context": None,
        },
        "derived_keys": {
            "sender_key": ctx.sender_key.hex(),
            "recipient_key": ctx.recipient_key.hex(),
            "common_iv": ctx.common_iv.hex(),
        },
        "request_protection": {
            "sequence": REQUEST_SEQUENCE,
            "code": REQUEST_CODE,
            "options": "",
            "payload": REQUEST_PAYLOAD.hex(),
            "expected": {
                "nonce": nonce.hex(),
                "ciphertext": ciphertext.hex(),
                "oscore_option": oscore_option.hex(),
            },
        },
    }

    OUTPUT.write_text(json.dumps(fixture, indent=2) + "\n")
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
