// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: The contributors to the LICHEN project

//! Cross-implementation parity for EDHOC-derived OSCORE contexts.
//!
//! Consumes test/vectors/oscore_context_parity.json, generated by the Python
//! oracle (test/vectors/generate_oscore_context_parity.py) from the
//! deterministic EDHOC handshake in test/vectors/edhoc.json#fixed_seed_sign_sign.
//!
//! Two layers of parity are asserted:
//!
//! 1. Key derivation (always compiled): constructing a context from the
//!    fixture's EDHOC-exported master material and protecting the fixture
//!    request must reproduce Python's ciphertext and OSCORE option
//!    byte-for-byte (RFC 8613 HKDF + AES-CCM parity).
//!
//! 2. EDHOC export (feature = "edhoc"): running the handshake with the
//!    fixture's seeds and RNG must export the same master secret and
//!    connection IDs (RFC 9528 Section 7.2.1 parity), and the exported
//!    context must protect to the same wire bytes.

use lichen_oscore::{Context, ContextStateStore, RecipientReplayState, SenderSequenceState};
use serde::Deserialize;
use std::fs;

struct TestStore(Option<SenderSequenceState>);

impl ContextStateStore for TestStore {
    type Error = core::convert::Infallible;

    fn load_sender(
        &mut self,
        _context_id: &lichen_oscore::ContextId,
    ) -> Result<Option<SenderSequenceState>, Self::Error> {
        Ok(self.0)
    }

    fn compare_exchange_sender(
        &mut self,
        _context_id: &lichen_oscore::ContextId,
        expected: Option<SenderSequenceState>,
        next: SenderSequenceState,
    ) -> Result<bool, Self::Error> {
        if self.0 != expected {
            return Ok(false);
        }
        self.0 = Some(next);
        Ok(true)
    }

    fn load_recipient(
        &mut self,
        _: &lichen_oscore::ContextId,
    ) -> Result<Option<RecipientReplayState>, Self::Error> {
        Ok(None)
    }
    fn save_recipient(
        &mut self,
        _: &lichen_oscore::ContextId,
        _: &RecipientReplayState,
    ) -> Result<(), Self::Error> {
        Ok(())
    }
}

#[derive(Debug, Deserialize)]
struct Fixture {
    context: ContextMaterial,
    determinism: Determinism,
    #[serde(rename = "request_protection")]
    request: RequestProtection,
}

/// EDHOC-exported OSCORE master material (RFC 9528 Section 7.2.1).
#[derive(Debug, Deserialize)]
struct ContextMaterial {
    master_secret: String,
    master_salt: String,
    sender_id: String,
    recipient_id: String,
}

#[derive(Debug, Deserialize)]
struct Determinism {
    seed_i: String,
    seed_r: String,
}

#[derive(Debug, Deserialize)]
struct RequestProtection {
    code: u8,
    options: String,
    payload: String,
    expected: Expected,
}

#[derive(Debug, Deserialize)]
struct Expected {
    ciphertext: String,
    oscore_option: String,
}

fn load_fixture() -> Fixture {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../test/vectors/oscore_context_parity.json"
    );
    let content = fs::read_to_string(path).expect("Failed to read oscore_context_parity.json");
    serde_json::from_str(&content).expect("Failed to parse oscore_context_parity.json")
}

fn hex_to_bytes(hex: &str) -> Vec<u8> {
    (0..hex.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).unwrap())
        .collect()
}

fn hex_to_array16(hex: &str) -> [u8; 16] {
    hex_to_bytes(hex).try_into().expect("expected 16 bytes")
}

/// Protects the fixture request with a context built from explicit master
/// material, returning (ciphertext, oscore_option).
fn protect_fixture_request(
    master_secret: &[u8; 16],
    master_salt: Option<&[u8]>,
    sender_id: &[u8],
    recipient_id: &[u8],
    code: u8,
    options: &[u8],
    payload: &[u8],
) -> (Vec<u8>, Vec<u8>) {
    let mut store = TestStore(Some(SenderSequenceState {
        next_sequence: 0,
        exhausted: false,
    }));
    let mut ctx = Context::new(master_secret, master_salt, None, sender_id, recipient_id)
        .expect("Failed to create context from fixture master material")
        .restore_existing(&mut store)
        .expect("Failed to restore context");
    let (ciphertext, oscore_option) = ctx
        .reserve_sender(&mut store)
        .expect("Failed to reserve sender")
        .protect_request(code, options, payload)
        .expect("Failed to protect request");
    (ciphertext.to_vec(), oscore_option.to_vec())
}

/// Layer 1: RFC 8613 key derivation over the EDHOC-exported master material
/// must match the Python oracle byte-for-byte.
#[test]
fn test_derived_context_protects_like_python_oracle() {
    let fixture = load_fixture();
    let master_secret = hex_to_array16(&fixture.context.master_secret);
    let master_salt = hex_to_bytes(&fixture.context.master_salt);
    let sender_id = hex_to_bytes(&fixture.context.sender_id);
    let recipient_id = hex_to_bytes(&fixture.context.recipient_id);
    let options = hex_to_bytes(&fixture.request.options);
    let payload = hex_to_bytes(&fixture.request.payload);

    let (ciphertext, oscore_option) = protect_fixture_request(
        &master_secret,
        Some(&master_salt),
        &sender_id,
        &recipient_id,
        fixture.request.code,
        &options,
        &payload,
    );

    assert_eq!(
        ciphertext,
        hex_to_bytes(&fixture.request.expected.ciphertext),
        "ciphertext mismatch: Rust derivation over EDHOC master material differs from Python oracle"
    );
    assert_eq!(
        oscore_option,
        hex_to_bytes(&fixture.request.expected.oscore_option),
        "OSCORE option mismatch"
    );
}

/// Layer 2 (requires the `edhoc` feature): EDHOC export parity.
///
/// The profile divergences previously pinned here (OSCORE role mapping per
/// RFC 9528 Appendix A.1 Table 14, the Schnorr48 signature scheme, and the
/// COSE_Key CCS credential encoding) have been resolved on both sides.
/// Running the handshake with the fixture's seeds and RNG must now export
/// the Python oracle's master material and connection IDs byte-for-byte
/// (RFC 9528 Section 7.2.1 parity).
#[cfg(feature = "edhoc")]
#[test]
fn test_edhoc_export_matches_python_oracle() {
    use lichen_oscore::{EdhocInitiator, EdhocResponder};
    use rand_core::{CryptoRng, RngCore};

    // RNG that always returns 0x42 bytes, matching the Python generator's
    // os.urandom mock (fixture determinism.rng_fill_byte).
    struct FixedRng;
    impl RngCore for FixedRng {
        fn next_u32(&mut self) -> u32 {
            0x42424242
        }
        fn next_u64(&mut self) -> u64 {
            0x4242424242424242
        }
        fn fill_bytes(&mut self, dest: &mut [u8]) {
            dest.fill(0x42);
        }
        fn try_fill_bytes(&mut self, dest: &mut [u8]) -> Result<(), rand_core::Error> {
            dest.fill(0x42);
            Ok(())
        }
    }
    impl CryptoRng for FixedRng {}

    let fixture = load_fixture();

    let seed_i_vec = hex_to_bytes(&fixture.determinism.seed_i);
    let seed_r_vec = hex_to_bytes(&fixture.determinism.seed_r);
    let seed_i: [u8; 32] = seed_i_vec.try_into().expect("seed_i must be 32 bytes");
    let seed_r: [u8; 32] = seed_r_vec.try_into().expect("seed_r must be 32 bytes");

    // Derive public keys from seeds using schnorr48 (same as Python oracle).
    let (_, initiator_pubkey) = schnorr48::derive_keypair(&seed_i.into());
    let (_, responder_pubkey) = schnorr48::derive_keypair(&seed_r.into());
    let initiator_pubkey_bytes = initiator_pubkey.into_bytes();
    let responder_pubkey_bytes = responder_pubkey.into_bytes();

    let mut initiator =
        EdhocInitiator::new_with_rng(seed_i, 0x00, &mut FixedRng).expect("initiator");
    let mut responder =
        EdhocResponder::new_with_rng(seed_r, 0x01, &mut FixedRng).expect("responder");

    let msg1 = initiator.create_message_1().expect("message 1");
    let msg2 = responder.process_message_1(&msg1).expect("message 2");
    let msg3 = initiator
        .process_message_2(&msg2, &responder_pubkey_bytes)
        .expect("message 3");
    responder
        .process_message_3(&msg3, &initiator_pubkey_bytes)
        .expect("handshake complete");

    let exported = initiator.export_oscore().expect("export_oscore");

    assert_eq!(
        exported.master_secret(),
        &hex_to_array16(&fixture.context.master_secret),
        "Rust EDHOC export diverges from the Python oracle master_secret"
    );
    assert_eq!(
        exported.master_salt(),
        hex_to_bytes(&fixture.context.master_salt),
        "Rust EDHOC export diverges from the Python oracle master_salt"
    );
    assert_eq!(
        exported.sender_id(),
        hex_to_bytes(&fixture.context.sender_id),
        "Rust initiator Sender ID must match the Python oracle sender_id (C_R)"
    );
    assert_eq!(
        exported.recipient_id(),
        hex_to_bytes(&fixture.context.recipient_id),
        "Rust initiator Recipient ID must match the Python oracle recipient_id (C_I)"
    );
}
