// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: The contributors to the LICHEN project

//! Spec-conformance mirror for GCP-6.5 COSE_Sign1 slot claims.
//!
//! Drives every case in `test/vectors/gcp_slot_claim_cose_sign1.json`
//! through the Rust decode (`RawSlotClaim::from_cose`) and verification
//! (`SlotClaimVerifier::verify`) paths. The JSON document is the oracle —
//! generated by an independent PyNaCl reference (see its `oracle` block);
//! never edit it to make a test pass.

use lichen_gateway::resources::validate_claim_timing;
use lichen_gateway::slot::{RawSlotClaim, SlotClaimVerifier, SlotError};
use serde_json::Value;

const VECTORS_JSON: &str = include_str!("../../../test/vectors/gcp_slot_claim_cose_sign1.json");

/// Per-superframe slot budget used for decoding; every corpus case stays
/// far below it (largest case claims slots 0..=59).
const SLOTS_PER_SUPERFRAME: u32 = 64;

fn hex_bytes(hex: &str) -> Vec<u8> {
    (0..hex.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).unwrap())
        .collect()
}

fn signer_pubkey(case: &Value) -> [u8; 32] {
    hex_bytes(case["signer_public_key_hex"].as_str().unwrap())
        .try_into()
        .unwrap()
}

#[test]
fn gcp_slot_claim_cose_sign1_corpus() {
    let document: Value = serde_json::from_str(VECTORS_JSON).expect("parse vector corpus");
    let evaluation_time = document["constants"]["evaluation_time"].as_i64().unwrap();

    // Seed envelope for the replay cases: the vector's receiver cached
    // claim_seq 5 from "claim_seq_cache_seed" (same signer, same
    // superframe), which is exactly what verify() records in last_seen.
    let cache_seed_envelope = hex_bytes(
        document["cases"]
            .as_array()
            .unwrap()
            .iter()
            .find(|case| case["name"].as_str() == Some("claim_seq_cache_seed"))
            .expect("corpus must contain the replay cache seed")["cose_sign1_hex"]
            .as_str()
            .unwrap(),
    );

    for case in document["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let envelope = hex_bytes(case["cose_sign1_hex"].as_str().unwrap());
        let pubkey = signer_pubkey(case);
        let superframe = case["superframe_epoch"].as_u64().unwrap();
        let reason = case["expected_reject_reason"].as_str().unwrap();
        // Redundant corpus field: every case carries expect_valid exactly
        // when the reject reason is "none". Guard it so a single-field flip
        // in the JSON (e.g. replay -> none) cannot go unnoticed.
        assert_eq!(
            reason == "none",
            case["expect_valid"].as_bool().unwrap(),
            "{name}: expect_valid / expected_reject_reason mismatch"
        );

        match reason {
            // Valid claim: structural decode carries the signed fields
            // byte-exact and the COSE-form signature verifies.
            "none" => {
                let claim = RawSlotClaim::from_cose(&envelope, SLOTS_PER_SUPERFRAME)
                    .unwrap_or_else(|e| panic!("{name}: decode failed: {e:?}"));
                let slots: Vec<u32> = case["slots"]
                    .as_array()
                    .unwrap()
                    .iter()
                    .map(|s| s.as_u64().unwrap() as u32)
                    .collect();
                assert_eq!(claim.slots(), &slots, "{name}");
                assert_eq!(claim.superframe_id(), superframe, "{name}");
                assert_eq!(
                    claim.claim_sequence(),
                    case["claim_seq"].as_u64().unwrap() as u32,
                    "{name}"
                );
                assert_eq!(claim.expiry(), case["expiry"].as_u64().unwrap(), "{name}");
                assert_eq!(claim.ordinal(), case["ordinal"].as_u64(), "{name}");
                let mut verifier = SlotClaimVerifier::new_ephemeral(64).unwrap();
                verifier
                    .verify(claim, &pubkey, superframe)
                    .unwrap_or_else(|e| panic!("{name}: verify failed: {e:?}"));
            }
            // Tampered signed payload: decodes fine, fails the signature
            // gate (verifier re-encodes the decoded fields, so the mutated
            // slots no longer match the signature).
            "signature" => {
                let claim = RawSlotClaim::from_cose(&envelope, SLOTS_PER_SUPERFRAME)
                    .unwrap_or_else(|e| panic!("{name}: decode failed: {e:?}"));
                let mut verifier = SlotClaimVerifier::new_ephemeral(64).unwrap();
                assert!(
                    matches!(
                        verifier.verify(claim, &pubkey, superframe),
                        Err(SlotError::InvalidSignature)
                    ),
                    "{name}: expected signature rejection"
                );
            }
            // Receiver cached claim_seq 5: seed a fresh verifier from the
            // cache-seed case, then the equal/lower claim_seq replays must
            // land in the Replay arm (GCP-6.5 step 8).
            "replay" => {
                let seed = RawSlotClaim::from_cose(&cache_seed_envelope, SLOTS_PER_SUPERFRAME)
                    .unwrap_or_else(|e| panic!("{name}: cache-seed decode failed: {e:?}"));
                let mut verifier = SlotClaimVerifier::new_ephemeral(64).unwrap();
                let seed_pubkey = signer_pubkey(
                    document["cases"]
                        .as_array()
                        .unwrap()
                        .iter()
                        .find(|case| case["name"].as_str() == Some("claim_seq_cache_seed"))
                        .unwrap(),
                );
                verifier
                    .verify(seed, &seed_pubkey, superframe)
                    .unwrap_or_else(|e| panic!("{name}: cache-seed verify failed: {e:?}"));

                let claim = RawSlotClaim::from_cose(&envelope, SLOTS_PER_SUPERFRAME)
                    .unwrap_or_else(|e| panic!("{name}: decode failed: {e:?}"));
                assert!(
                    matches!(
                        verifier.verify(claim, &pubkey, superframe),
                        Err(SlotError::Replay { .. })
                    ),
                    "{name}: expected replay rejection"
                );
            }
            // Structurally valid; the claim-horizon gate (validate_claim_
            // timing, spec/08 GCP-6.5 step 7a — handler-side in Rust,
            // verify-slot-claim side in Python) rejects expiry <= now.
            "expired" => {
                RawSlotClaim::from_cose(&envelope, SLOTS_PER_SUPERFRAME)
                    .unwrap_or_else(|e| panic!("{name}: decode failed: {e:?}"));
                let expiry = case["expiry"].as_i64().unwrap();
                assert!(
                    !validate_claim_timing(expiry, evaluation_time),
                    "{name}: expired claim must fail the timing gate"
                );
            }
            // Validation step 4: any alg other than -65537 is a decoy.
            "algorithm" => {
                assert_eq!(
                    RawSlotClaim::from_cose(&envelope, SLOTS_PER_SUPERFRAME).unwrap_err(),
                    SlotError::UnsupportedAlgorithm,
                    "{name}: expected algorithm decoy rejection"
                );
            }
            // The unprotected kid must equal the payload's gateway_iid.
            "kid_payload_mismatch" => {
                assert_eq!(
                    RawSlotClaim::from_cose(&envelope, SLOTS_PER_SUPERFRAME).unwrap_err(),
                    SlotError::IdentityMismatch,
                    "{name}: expected kid/payload IID mismatch rejection"
                );
            }
            // Keys 1-7 are all required: without the ordinal the receiver
            // cannot register the gateway.
            "ordinal_missing" => {
                assert_eq!(
                    RawSlotClaim::from_cose(&envelope, SLOTS_PER_SUPERFRAME).unwrap_err(),
                    SlotError::MalformedClaim,
                    "{name}: expected missing-ordinal rejection"
                );
            }
            other => panic!("unknown expected_reject_reason in corpus: {other}"),
        }
    }
}

#[test]
fn gcp_slot_claim_expiry_future_passes_timing_gate() {
    // The corpus pairs each expired case with an in-window twin;
    // assert the positive boundary here so the timing gate is checked
    // from both sides against the same oracle constants.
    let doc: Value = serde_json::from_str(VECTORS_JSON).expect("parse vector corpus");
    let evaluation_time = doc["constants"]["evaluation_time"].as_i64().unwrap();
    let case = doc["cases"]
        .as_array()
        .unwrap()
        .iter()
        .find(|case| case["name"].as_str() == Some("expiry_boundary_future"))
        .unwrap();
    assert!(validate_claim_timing(
        case["expiry"].as_i64().unwrap(),
        evaluation_time
    ));
}
