# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: The contributors to the LICHEN project

[target.thumbv7em-none-eabi]
runner = "probe-rs run --chip STM32WL55JCIx"

[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "info"
