// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: The contributors to the LICHEN project

//! Compile-time assertions that owned key material is zeroized on drop.
//!
//! OSCORE contexts hold the master secret, derived sender/recipient keys, and
//! the IV; EDHOC transcript hashing leaves SHA-256 state that has hashed
//! key-bearing messages. Each assertion below pins the corresponding
//! zeroization guarantee at compile time: if a dependency change drops it,
//! the build fails here instead of key material silently surviving in freed
//! memory.
//!
//! Coverage notes:
//!
//! - [`Sha256`] is pinned as [`ZeroizeOnDrop`] through the `sha2/zeroize`
//!   feature (digest's zeroize support). Upstream `hkdf` 0.13 exposes no
//!   `zeroize` feature, so its PRK output buffer is not covered here.
//! - [`Aes128`] is pinned as [`ZeroizeOnDrop`] through the direct
//!   `aes/zeroize` dependency feature. `ccm` 0.5 has no zeroize feature, so
//!   the CCM wrapper state itself is not covered.
//! - For HMAC (used inside HKDF-SHA-256), upstream `hmac` 0.13 does not opt
//!   its `Hmac`/`HmacCore` types into `ZeroizeOnDrop` (its `buffer_fixed!`
//!   invocation omits the trait). The `hmac/zeroize` feature still enables
//!   `digest/zeroize`, under which the key-derived ipad/opad hash cores and
//!   the [`CtOutput`] tag are [`ZeroizeOnDrop`]; the pad-bearing cores
//!   zeroize transitively when an `Hmac` instance drops. The tag output type
//!   is pinned here; pin `Hmac` itself once upstream opts in.
//! - [`Context`](crate::Context) is pinned as [`Zeroize`]: it zeroizes on
//!   drop via its `Drop` impl (generated by the deprecated
//!   `#[zeroize(drop)]` derive attribute, which does not emit the
//!   [`ZeroizeOnDrop`] marker). Once the `oscore` crate adopts
//!   `#[derive(ZeroizeOnDrop)]`, tighten this to
//!   [`assert_zeroize_on_drop`].
//! - [`KeyUpdateContext`](crate::KeyUpdateContext) is deliberately *not*
//!   `ZeroizeOnDrop`: it exposes `into_context` (a field move out of
//!   `self`), which a `Drop` impl would forbid (E0509). Its key material is
//!   still zeroized, transitively, by the inner `Context`'s zeroizing drop.

use zeroize::{Zeroize, ZeroizeOnDrop};

/// Compile-time assertion: `T` must implement [`ZeroizeOnDrop`].
///
/// A call that fails to compile means `T` no longer zeroizes its owned
/// state on drop.
const fn assert_zeroize_on_drop<T: ZeroizeOnDrop>() {}

/// Compile-time assertion: `T` must implement [`Zeroize`].
const fn assert_zeroize<T: Zeroize>() {}

// OSCORE context (re-exported from the `oscore` crate): master secret,
// derived sender/recipient keys, and IV. Zeroized on drop via its `Drop`
// impl; see the module notes for the missing `ZeroizeOnDrop` marker.
const _: () = assert_zeroize::<crate::Context>();

// SHA-256 hasher state used for EDHOC transcript hashes (RFC 9528 Suite 0),
// pinned by the `sha2/zeroize` dependency feature.
const _: () = assert_zeroize_on_drop::<sha2::Sha256>();

// AES-128 cipher state (round keys) used by AES-CCM-16-64-128 (RFC 8613
// A.1), pinned by the `aes/zeroize` dependency feature.
const _: () = assert_zeroize_on_drop::<aes::Aes128>();

// HMAC-SHA-256 MAC tag output (key-derived secret) used inside
// HKDF-SHA-256 (RFC 8613 Section 5 / RFC 5869), pinned by the
// `hmac/zeroize` dependency feature (digest's zeroize support). Upstream
// `hmac` 0.13 does not mark `Hmac` itself `ZeroizeOnDrop`; see the module
// notes.
const _: () = assert_zeroize_on_drop::<hmac::digest::CtOutput<hmac::Hmac<sha2::Sha256>>>();
